### ISSUE TITLE
TypeError: Cannot read property 'promise' of undefined

### ISSUE THREAD

**Issue by abakasam** [abakasam/abakasam#104]
https://www.pluralsight.com/guides/javascript-promise-typeerror:-cannot-read-then-of-undefined
https://www.twilio.com/blog/how-to-read-and-understand-a-java-stacktrace

C:\Users\Administrator\Desktop\ionic\package\lib\ionic.js:684:20

ionic.js 684
{ IONIC_DASH: 'https://apps.ionic.io',
  IONIC_API: '/api/v1/',
  PRIVATE_PATH: '.ionic',
  _tryBuildingTask: [Function],
  _getTaskWithName: [Function],
  printUsage: [Function],
  _printAvailableTasks: [Function],
  _printHelpLines: [Function],
  _printIonic: [Function],
  run: [Function],
  fail: [Function],
  version: [Function],
  checkLatestVersion: [Function],
  printVersionWarning: [Function],
  printNewsUpdates: [Function: printNewsUpdates],
  processExit: [Function],
  getContentSrc: [Function],
  fetchArchive: [Function],
  setConfigXml: [Function],
  latestVersion: 
   defer {
     promise: { state: 'fulfilled', value: undefined },
     resolve: [Function],
     fulfill: [Function],
     reject: [Function],
     notify: [Function] } }

**Comment by abakasam** [comment]
found files missing or needing to compile io.js myself

**Comment by abakasam** [comment]
having to compile right gcc for python 2.7.9

**Comment by abakasam** [comment]
existing ISSUE
cliNews
C:\Users\Administrator\OneDrive\Desktop\ionic\ionic\lib\ionic.js
line 684

this = { IONIC_DASH: 'https://apps.ionic.io',
  IONIC_API: '/api/v1/',
  PRIVATE_PATH: '.ionic',
  _tryBuildingTask: [Function],
  _getTaskWithName: [Function],
  printUsage: [Function],
  _printAvailableTasks: [Function],
  _printHelpLines: [Function],
  _printIonic: [Function],
  run: [Function],
  fail: [Function],
  version: [Function],
  checkLatestVersion: [Function],
  printVersionWarning: [Function],
  printNewsUpdates: [Function: printNewsUpdates],
  processExit: [Function],
  getContentSrc: [Function],
  fetchArchive: [Function],
  setConfigXml: [Function],
  latestVersion:
   defer {
     promise: { state: 'fulfilled', value: undefined },
     resolve: [Function],
     fulfill: [Function],
     reject: [Function],
     notify: [Function] } }
     

this.lastestVersion.defer.promise
this.cliNews.promise? missing
node 3.3.1
ionic 1.3.4
replaced this.cliNew.promise with this.lastestVersion.promise

https://github.com/nodejs/iojs.org
7 years ago of 11/20

**Comment by abakasam** [comment]
iojs 3.3.1

**Comment by abakasam** [comment]
You have to run from the .js not ionic

node ionic/lib/ionic/start.js
node ionic/bin/ionic

Script started on Wed Dec 29 21:58:32 2021
]0;cabox@Aquaogen:~/workspace/ionic/lib/ionic[?1034h[cabox@Aquaogen ionic]$ /home/cabox/workspace/iojs/node server.js[2@database.js[2Pserver.js         start
/home/cabox/workspace/ionic/node_modules/request/node_modules/tough-cookie/lib/cookie.js:40
const { fromCallback } = require("universalify");
                     ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/cabox/workspace/ionic/node_modules/request/lib/cookies.js:3:13)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
]0;cabox@Aquaogen:~/workspace/ionic/lib/ionic[cabox@Aquaogen ionic]$ exit

**Comment by abakasam** [comment]
Identified tough-cookie, invalid version

**Comment by abakasam** [comment]
https://www.redhat.com/sysadmin/linux-script-command

**Comment by abakasam** [comment]
request, package.json

    "tunnel-agent": "~0.4.0",
    "tough-cookie": ">=0.12.0",
    "http-signature": "~0.10.0",
    "oauth-sign": "~0.5.0",

    "tunnel-agent": "~0.4.0",
    "tough-cookie": "0.12.0",
    "http-signature": "~0.10.0",
    "oauth-sign": "~0.5.0",

npm install for request
request/node_modules/tough-cookie
request/node_modules/tough-cookie.backup

**Comment by abakasam** [comment]
echo $PATH
PATH=$PATH:/home/cabox/workspace/iojs
node

**Comment by abakasam** [comment]
phantomjs install fail

kew.resolve(true)
  .then(tryPhantomjsInLib)
  .then(tryPhantomjsOnPath)
  .then(downloadPhantomjs)
  .then(extractDownload)
  .then(function (extractedPath) {
    return copyIntoPlace(extractedPath, pkgPath)
  })
  .then(function () {
    var location = getTargetPlatform() === 'win32' ?
        path.join(pkgPath, 'phantomjs.exe') :
        path.join(pkgPath, 'bin' ,'phantomjs')

    try {
      // Ensure executable is executable by all users
      fs.chmodSync(location, '755')
    } catch (err) {
      if (err.code == 'ENOENT') {
        console.error('chmod failed: phantomjs was not successfully copied to', location)
        exit(1)
      }
      throw err
    }

    var relativeLocation = path.relative(libPath, location)
    writeLocationFile(relativeLocation)

    console.log('Done. Phantomjs binary available at', location)
    exit(0)
  })
  .fail(function (err) {
    console.error('Phantom installation failed', err, err.stack)
    exit(1)
  })

https://phantomjs.org/download.html

**Comment by abakasam** [comment]
https://github.com/ariya/phantomjs/tree/master
